name: house_rent_app
description: A simple offline-only app to save house rent information with photos and GPS.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^0.8.7+4
  geolocator: ^9.0.2
  flutter_compass: ^0.8.1
  uuid: ^3.0.6
  url_launcher: ^6.1.7
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.1.1
  path_provider: ^2.0.11
  exif: ^2.0.1
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.4
  permission_handler: ^11.0.0

  wifi_iot: ^0.3.19
  flutter_contacts: ^1.1.9

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.5
  mobile_scanner: ^7.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/models/
